"""agregar campos numero  a Mesa

Revision ID: b41c8e7d284c
Revises: 
Create Date: 2025-07-24 18:22:56.045145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41c8e7d284c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mesas', schema=None) as batch_op:
        batch_op.drop_column('numero')

    # ### end Alembic commands ###
